# Generated by Django 6.0.2 on 2026-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='description',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='is_general_knowledge',
        ),
        migrations.AddField(
            model_name='concept',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='knowledge.concept'),
        ),
    ]
