# Generated by Django 6.0.2 on 2026-04-17 12:41

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_studentconceptmastery'),
        ('uploads', '0002_subject_document_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='chunk_index',
        ),
        migrations.AddField(
            model_name='concept',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='uploads.subject'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together={('subject', 'name')},
        ),
    ]
