# Generated by Django 6.0.2 on 2026-04-18 16:56

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_alter_concept_options_and_more'),
        ('uploads', '0002_subject_document_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['chunk_index']},
        ),
        migrations.AddField(
            model_name='concept',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='concept',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepts', to='uploads.document'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='conceptrelation',
            unique_together={('from_concept', 'to_concept', 'relation_type')},
        ),
        migrations.DeleteModel(
            name='StudentConceptMastery',
        ),
    ]
