# Generated by Django 6.0.2 on 2026-04-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerconceptmastery',
            name='hint_level',
            field=models.IntegerField(default=0),
        ),
    ]
