# Generated by Django 6.0.2 on 2026-03-30 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('TEACH', 'Teach'), ('CHECK', 'Check'), ('REMEDIATE', 'Remediate'), ('REINFORCE', 'Reinforce')], default='TEACH', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tutoring.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user_answer', models.TextField(blank=True)),
                ('score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.concept')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='tutoring.studysession')),
            ],
        ),
    ]
