# Generated by Django 6.0.2 on 2026-04-02 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptcheck',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='conceptcheck',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='conceptcheck',
            name='score',
        ),
        migrations.RemoveField(
            model_name='conceptcheck',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='conceptcheck',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptcheck',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptcheck',
            name='source_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_concept_checks', to='tutoring.studymessage'),
        ),
        migrations.AddField(
            model_name='conceptcheck',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('evaluated', 'Evaluated')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='conceptcheck',
            name='concept',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='conceptcheck',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_checks', to='tutoring.studysession'),
        ),
        migrations.CreateModel(
            name='ConceptCheckAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('feedback', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, choices=[('correct', 'Correct'), ('partial', 'Partial'), ('incorrect', 'Incorrect')], max_length=20, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tutoring.conceptcheck')),
            ],
        ),
    ]
