# Generated by Django 6.0.2 on 2026-04-02 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_initial'),
        ('tutoring', '0002_remove_conceptcheck_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptcheck',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_checks', to='knowledge.concept'),
        ),
    ]
