# Generated by Django 6.0.2 on 2026-04-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_alter_conceptcheck_concept'),
        ('tutoring', '0004_conceptcheck_cancelled_fields'),
    ]

    operations = [
    ]
