# Generated by Django 6.0.2 on 2026-04-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_merge_20260409_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptcheck',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('evaluated', 'Evaluated'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
